### ISSUE TITLE
Trouble creating tbd for IPConfiguration

### ISSUE THREAD

**Issue by malhal** [Siguza/tbdump#5]
Hi I'd like to create a tbd for `/System/Library/SystemConfiguration/IPConfiguration.bundle/IPConfiguration` but tbdump errors with "File is not a dylib" which is strange because I can load it like:

`libHandle = dlopen("/System/Library/SystemConfiguration/IPConfiguration.bundle/IPConfiguration", RTLD_LAZY);`

From [here](https://github.com/devinshively/wifiAssociate/blob/master/wifiConnect43/SOLStumbler.m)

**Comment by Siguza** [comment]
If you have the file as a standalone binary, consider using `xcrun tapi stubify` instead.  
TBD files have seen multiple major revisions, and my tool hasn't kept up at all. :/

**Comment by malhal** [comment]
Hi thanks for the message, that yields similar error: "is not a dynamic library".

**Comment by Siguza** [comment]
Had a look at the file, and it is indeed not a dylib. If you look at `<mach-o/loader.h>`:

```c
#define MH_OBJECT       0x1 /* relocatable object file */
#define MH_EXECUTE      0x2 /* demand paged executable file */
#define MH_FVMLIB       0x3 /* fixed VM shared library file */
#define MH_CORE         0x4 /* core file */
#define MH_PRELOAD      0x5 /* preloaded executable file */
#define MH_DYLIB        0x6 /* dynamically bound shared library */
#define MH_DYLINKER     0x7 /* dynamic link editor */
#define MH_BUNDLE       0x8 /* dynamically bound bundle file */
#define MH_DYLIB_STUB   0x9 /* shared library stub for static linking only, no section contents */
#define MH_DSYM         0xa /* companion file with only debug sections */
#define MH_KEXT_BUNDLE  0xb /* x86_64 kexts */
```

The thing you're looking at is an `MH_BUNDLE` rather than an `MH_DYLIB`. The reason why it works with `dlopen` is because that is how it's _meant_ to be used: plugin-style.

So even if you manually wrote a .tbd file and linked against it, your binary would fail to be linked because a) the thing you try to link against isn't a dylib, and even if you patched that, b) it doesn't have an `LC_ID_DYLIB` load command. It's just... not meant to be linked against. :/
